import json

def add_provenance_footer(text: str, prov: dict, opts: dict) -> str:
    if not opts.get("embed_footer", True):
        return text
    block = {
        "palimpsest_provenance": prov
    }
    if opts.get("include_config"):
        block["note"] = "Generated by palimpsest-bot; stylistic/cryptographic rendering only."
    footer = "\n\n---\n" + json.dumps(block, ensure_ascii=False, indent=2) + "\n"
    return text + footer
